<?php

namespace AppBundle\Repository;

/**
 * PayLimitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayLimitsRepository extends \Doctrine\ORM\EntityRepository
{
}
