app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
  prefix: /admin
  resource: "@AppBundle/routing/admin_routes.yml"
  type: yaml

pay:
  prefix: /pay
  resource: "@AppBundle/routing/pay_routes.yml"
  type: yaml